language: ruby
script:
- echo hola
notifications:
  slack:
    on_pull_requests: false
    secure: tzl1PpZo+/o6bRzBACV7yIFvmLiri5NrucyjECQKPtmwhmMkQTIk3mwUPjtG6fu4iwj6F8SAYmiIkbmO6uKaI6yr1R2k0dIZ6TvaL3ObohfloBijFMvn3pP/amKUVQq942zRkYhlI2ljegBTlqlPBYnCRQ2e2XQgJkpM4duKbHmfz8YczqCt8kmbRLC0//FsSQLP8KHXrWydgja6RxStHJotbkGYDMOT1BXZ7lNojmgKEr49VZ3KXx0DouXDuzDln2NCg2J7f15qeypU7AQipv7P4+9m5nVaOx7xSWU67BmXNPEdn8yFE53YQWi9VBKBnhTkIJFINUKHVmMSrIqLrgK6pOq7Miy30ouEZHTcseKJqa5pGU0VOEU2tt7SE2qfuy95TxFLJElBHxk3ST0Yrla1geAdk1gVPLmpOevhBMnLOZI7AfX79Oa5tNNt8+36EuZod8IaZNMoPUi7pZ6vgOADDiMLFH1YbHwPwaNaxI3uq089COv3hrfv2gnXZJaIDX+nHhT1UiRg1q1my1N6CHIAxzrQpDnkiQbM98sb7DTVBHFNC+k2Io3WcHYQXxbnlUqCBur2b2h6o3AQSLI7P57pPzlJmNmwVpB6kAZZ8q0+cOoJyVNmxwSnNMAJmhwtGEAUcvGZeunJdC/GeUWOegEkuUgrurn9iTe7TDvO+sk=
