language: ruby

sudo: false

install:
  - true

script:
  - true

notifications:
  irc:
    channels:
      - secure: "dSznAbLrYmUG1mAAPYi453v4YzMW9zca3RawHrtpvmdLytTAxAxIYhmgG17XLlCO1qT+9/bYaAIYk/JETatxbjI1mi8KIsd6S50pdZaKPtkhLGugU46/5kR7sBq8J4kVOB5MOmVNfrRSHIAOukCb3YZ9j4YUB9CcSyLscKny83c="

