language: ruby

sudo: false

install:
  - true

script:
  - true

notifications:
  irc:
    channels:
      - secure: "kHjfGONwZsQBFaXJMkHt69EEy6f7jBZXLR9PFt+93pLyCvii48/gHgQ59jaati/XrVr8TklV5B77eaL9FXYa3GmMaRdN/3sNtFQ4K71lIVRvakG0nVZjpU4YGkd+gQu+F2Cx7b6qQYuIPRlbNy+hufx05PxEvggno0k5ftLn1J8="
  slack:
    rooms:
      - secure: "U5pvtq/KfoiTC08p8qCAvA4mB4b3/klt03GFsQuFApHm6MYL3YRw+u3451ma19j77/a3g+fPB6QU0R+5l7kBwyItNjMBm2hhSK+IeJYfgM0H2rh8zc/91i+N4X0E+hcb8ACDduJyV/5ychmvss5N9oHM25dRMSzrE6HGpSl+QKc="

