language: node_js

sudo: false

node_js:
  - '0.10'

before_install:
  - eval "npm install -g npm@$(jq .engines.npm package.json)"
  - npm --version

install:
  - true

script:
  - true

deploy:
  provider: script
  edge:
    branch: 'v1.8.2'
  script: bash sleep.sh
  on:
    all_branches: true
